# Generated by Django 3.2 on 2021-04-16 06:03

import comment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20210416_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='order_number',
            field=models.CharField(default=comment.models.random_string, editable=False, max_length=7),
        ),
    ]
